In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

df = pd.read_csv('iris/iris.data', header=None, names=names)
X = np.array(df.iloc[:, 0:4])
y = np.array(df['class'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)

print('\nModel accuracy score: ', accuracy_score(y_test, pred))
print('\nFrom the test data')
for i in range(len(pred)):
    if pred[i] != y_test[i]:
        print(i, '\t', pred[i], '\t', y_test[i], ' ****')

print('\n Confusion Matrix\n', confusion_matrix(y_test, pred))


Model accuracy score:  0.9777777777777777

From the test data
43 	 Iris-versicolor 	 Iris-virginica  ****

 Confusion Matrix
 [[15  0  0]
 [ 0 13  0]
 [ 0  1 16]]
